[package]
name = "market"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
chrono = "0.4.39"
tokio = { version = "1.43.0", features = ["full"] }
uuid = { version = "1.12.1", features = ["v4"] }
